
-- 1. 데이터베이스(계정) 생성 이미 만들어져 있으면 테이블 생성으로 이동
show user;
-- 12c 버전 부터는 아래 문장 실행후 계정 생성 
 ALTER SESSION SET "_ORACLE_SCRIPT"=true; 
 
 -- 계정(데이터베이스) 생성
create user ums identified by 1234;  

-- 새로 만든 계정(데이터베이스)에 권한 부역
grant all privileges to ums;

-- 사용자 테이블 스페이스 사용 권한 부여
alter user ums default tablespace users quota unlimited on users;

--------------------------------------------------------
--  ������ ������ - ȭ����-11��-15-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence SEQ_BBS_NO
--------------------------------------------------------

   CREATE SEQUENCE  "UMS"."SEQ_BBS_NO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CATEGORY
--------------------------------------------------------

   CREATE SEQUENCE  "UMS"."SEQ_CATEGORY"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CLIENT
--------------------------------------------------------

   CREATE SEQUENCE  "UMS"."SEQ_CLIENT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence SEQ_DEPARTMENT
--------------------------------------------------------

   CREATE SEQUENCE  "UMS"."SEQ_DEPARTMENT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence SEQ_INVOICEHEADER
--------------------------------------------------------

   CREATE SEQUENCE  "UMS"."SEQ_INVOICEHEADER"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence SEQ_INVOICE_DETAIL
--------------------------------------------------------

   CREATE SEQUENCE  "UMS"."SEQ_INVOICE_DETAIL"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence SEQ_PRODUCT
--------------------------------------------------------

   CREATE SEQUENCE  "UMS"."SEQ_PRODUCT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence SEQ_ROLE
--------------------------------------------------------

   CREATE SEQUENCE  "UMS"."SEQ_ROLE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence SEQ_USERS
--------------------------------------------------------

   CREATE SEQUENCE  "UMS"."SEQ_USERS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence SEQ_USER_ROLE_ID
--------------------------------------------------------

   CREATE SEQUENCE  "UMS"."SEQ_USER_ROLE_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Sequence employees_seq
--------------------------------------------------------

   CREATE SEQUENCE  "UMS"."employees_seq"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE   ;
--------------------------------------------------------
--  DDL for Table BBS
--------------------------------------------------------

  CREATE TABLE "UMS"."BBS" 
   (	"NO" NUMBER(5,0), 
	"TITLE" VARCHAR2(100 BYTE), 
	"CONTENT" VARCHAR2(1000 BYTE), 
	"WRITER" VARCHAR2(50 BYTE), 
	"HIT" NUMBER(5,0) DEFAULT 0, 
	"REGDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CATEGORY
--------------------------------------------------------

  CREATE TABLE "UMS"."CATEGORY" 
   (	"CATEGORY_ID" NUMBER, 
	"CATEGORY_NAME" VARCHAR2(100 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"IS_ACTIVE" CHAR(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "UMS"."CLIENT" 
   (	"CLIENT_ID" NUMBER(5,0), 
	"CLIENT_NAME" VARCHAR2(100 BYTE), 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"POSTAL_CODE" VARCHAR2(5 BYTE), 
	"PHONE" VARCHAR2(15 BYTE), 
	"FAX" VARCHAR2(15 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"IS_ACTIVE" CHAR(3 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEPARTMENT
--------------------------------------------------------

  CREATE TABLE "UMS"."DEPARTMENT" 
   (	"DEPT_ID" NUMBER(5,0), 
	"DEPT_NAME" VARCHAR2(20 BYTE), 
	"PARENT_ID" NUMBER(3,0), 
	"MANAGED_ID" NUMBER(3,0), 
	"LOCATION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEES
--------------------------------------------------------

  CREATE TABLE "UMS"."EMPLOYEES" 
   (	"EMPLOYEE_ID" NUMBER(6,0), 
	"FIRST_NAME" VARCHAR2(20 BYTE), 
	"LAST_NAME" VARCHAR2(25 BYTE), 
	"EMAIL" VARCHAR2(25 BYTE), 
	"PHONE_NUMBER" VARCHAR2(20 BYTE), 
	"HIRE_DATE" DATE, 
	"JOB_ID" VARCHAR2(10 BYTE), 
	"SALARY" NUMBER(8,2), 
	"COMMISSION_PCT" NUMBER(2,2), 
	"MANAGER_ID" NUMBER(6,0), 
	"DEPT_ID" NUMBER(4,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INVOICEDETAIL
--------------------------------------------------------

  CREATE TABLE "UMS"."INVOICEDETAIL" 
   (	"INVOICE_DETAIL_ID" NUMBER(5,0), 
	"INVOICE_ID" NUMBER(5,0), 
	"PRODUCT_ID" NUMBER(5,0), 
	"UNIT_PRICE" NUMBER(10,0) DEFAULT 0, 
	"QUANTITY" NUMBER(5,0) DEFAULT 0, 
	"TOTAL_AMT" NUMBER(10,0) DEFAULT 0, 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"MODIFIED_DATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INVOICEHEADER
--------------------------------------------------------

  CREATE TABLE "UMS"."INVOICEHEADER" 
   (	"INVOICE_ID" NUMBER(5,0), 
	"CLIENT_ID" NUMBER, 
	"SHIPPING_ADDRESS" VARCHAR2(200 BYTE), 
	"TOTAL_AMT" NUMBER(10,0), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"CREATED_DATE" DATE DEFAULT sysdate, 
	"MODIFIED_DATE" DATE DEFAULT sysdate, 
	"INVOICE_DATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table JOBS
--------------------------------------------------------

  CREATE TABLE "UMS"."JOBS" 
   (	"JOB_ID" VARCHAR2(10 BYTE), 
	"JOB_TITLE" VARCHAR2(35 BYTE), 
	"MIN_SALARY" NUMBER(6,0), 
	"MAX_SALARY" NUMBER(6,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PERSISTENT_LOGINS
--------------------------------------------------------

  CREATE TABLE "UMS"."PERSISTENT_LOGINS" 
   (	"USER_ID" VARCHAR2(15 BYTE), 
	"SERIES" VARCHAR2(64 BYTE), 
	"TOKEN" VARCHAR2(64 BYTE), 
	"LAST_USED" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCT
--------------------------------------------------------

  CREATE TABLE "UMS"."PRODUCT" 
   (	"PRODUCT_ID" NUMBER(5,0), 
	"PRODUCT_NAME" VARCHAR2(100 BYTE), 
	"BRAND" VARCHAR2(100 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"UNIT_PRICE" NUMBER(10,0) DEFAULT 0, 
	"CATEGORY_ID" NUMBER, 
	"IS_ACTIVE" CHAR(3 BYTE), 
	"RECEIPT_DATE" DATE DEFAULT sysdate
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ROLE
--------------------------------------------------------

  CREATE TABLE "UMS"."ROLE" 
   (	"ROLE_ID" VARCHAR2(15 BYTE), 
	"ROLE_NAME" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "UMS"."USERS" 
   (	"USER_NO" NUMBER(5,0), 
	"USER_ID" VARCHAR2(15 BYTE), 
	"USER_PWD" VARCHAR2(200 BYTE), 
	"USER_NAME" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PHONE" VARCHAR2(15 BYTE), 
	"FAX" VARCHAR2(15 BYTE), 
	"ZIP_NUM" CHAR(7 BYTE), 
	"ADDRESS1" VARCHAR2(50 BYTE), 
	"ADDRESS2" VARCHAR2(50 BYTE), 
	"DEPT_ID" NUMBER(5,0), 
	"ROLE_ID" VARCHAR2(15 BYTE), 
	"IMAGE_PATH" VARCHAR2(50 BYTE), 
	"USEYN" CHAR(3 BYTE) DEFAULT '1', 
	"REGDATE" DATE DEFAULT sysdate, 
	"MODDATE" DATE DEFAULT sysdate, 
	"ENAVLED" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USER_ROLE
--------------------------------------------------------

  CREATE TABLE "UMS"."USER_ROLE" 
   (	"USER_ROLE_ID" NUMBER(5,0), 
	"USER_ID" VARCHAR2(15 BYTE), 
	"ROLE_ID" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into UMS.BBS
SET DEFINE OFF;
Insert into UMS.BBS (NO,TITLE,CONTENT,WRITER,HIT,REGDATE) values (1,'����','�����Դϴ�.','�ۼ���1',1,to_date('22/11/14','RR/MM/DD'));
Insert into UMS.BBS (NO,TITLE,CONTENT,WRITER,HIT,REGDATE) values (2,'����2','�����Դϴ�.','�ۼ���2',2,to_date('22/11/02','RR/MM/DD'));
REM INSERTING into UMS.CATEGORY
SET DEFINE OFF;
Insert into UMS.CATEGORY (CATEGORY_ID,CATEGORY_NAME,DESCRIPTION,IS_ACTIVE) values (1,'Electronic','Electronic description','1  ');
Insert into UMS.CATEGORY (CATEGORY_ID,CATEGORY_NAME,DESCRIPTION,IS_ACTIVE) values (2,'Household','Household description','1  ');
Insert into UMS.CATEGORY (CATEGORY_ID,CATEGORY_NAME,DESCRIPTION,IS_ACTIVE) values (3,'Vehicle','Vehicle description','1  ');
Insert into UMS.CATEGORY (CATEGORY_ID,CATEGORY_NAME,DESCRIPTION,IS_ACTIVE) values (4,'Computer','Computer description','1  ');
Insert into UMS.CATEGORY (CATEGORY_ID,CATEGORY_NAME,DESCRIPTION,IS_ACTIVE) values (5,'Food','Food description','1  ');
Insert into UMS.CATEGORY (CATEGORY_ID,CATEGORY_NAME,DESCRIPTION,IS_ACTIVE) values (21,'New Category','New Category','1  ');
Insert into UMS.CATEGORY (CATEGORY_ID,CATEGORY_NAME,DESCRIPTION,IS_ACTIVE) values (22,'New Category10','New Category1 description','1  ');
REM INSERTING into UMS.CLIENT
SET DEFINE OFF;
Insert into UMS.CLIENT (CLIENT_ID,CLIENT_NAME,ADDRESS,POSTAL_CODE,PHONE,FAX,EMAIL,IS_ACTIVE) values (1,'SAMSUNG','SEOUL','29387','02-3383-4948',null,'ahnjunggeun@naver.com','1  ');
Insert into UMS.CLIENT (CLIENT_ID,CLIENT_NAME,ADDRESS,POSTAL_CODE,PHONE,FAX,EMAIL,IS_ACTIVE) values (2,'LG Electronic','NEW YORK 3837-3','33736','02-4848-4949',null,'kingsejong@daum.net','1  ');
Insert into UMS.CLIENT (CLIENT_ID,CLIENT_NAME,ADDRESS,POSTAL_CODE,PHONE,FAX,EMAIL,IS_ACTIVE) values (3,'SK','PARIS 100-2','38376','02-3983-3837',null,'generalleeseunshin@google.com','1  ');
Insert into UMS.CLIENT (CLIENT_ID,CLIENT_NAME,ADDRESS,POSTAL_CODE,PHONE,FAX,EMAIL,IS_ACTIVE) values (4,'HYUNDAI','TOKOY 93-1','37367','02-3033-4487',null,'yoonbonggil@yahoo.com','1  ');
Insert into UMS.CLIENT (CLIENT_ID,CLIENT_NAME,ADDRESS,POSTAL_CODE,PHONE,FAX,EMAIL,IS_ACTIVE) values (5,'HANHWA','ITALY 332-1','38377','02-393-3938',null,'leebongchang@lycos.com','1  ');
REM INSERTING into UMS.DEPARTMENT
SET DEFINE OFF;
Insert into UMS.DEPARTMENT (DEPT_ID,DEPT_NAME,PARENT_ID,MANAGED_ID,LOCATION) values (1,'Administration',null,null,'SEOUL');
Insert into UMS.DEPARTMENT (DEPT_ID,DEPT_NAME,PARENT_ID,MANAGED_ID,LOCATION) values (2,'CM',null,null,'BUSAN');
Insert into UMS.DEPARTMENT (DEPT_ID,DEPT_NAME,PARENT_ID,MANAGED_ID,LOCATION) values (3,'Planning',null,null,'GWANGJOO');
Insert into UMS.DEPARTMENT (DEPT_ID,DEPT_NAME,PARENT_ID,MANAGED_ID,LOCATION) values (4,'Production',null,null,'DAEJEON');
Insert into UMS.DEPARTMENT (DEPT_ID,DEPT_NAME,PARENT_ID,MANAGED_ID,LOCATION) values (5,'Purchasing',null,null,'DAEGOO');
Insert into UMS.DEPARTMENT (DEPT_ID,DEPT_NAME,PARENT_ID,MANAGED_ID,LOCATION) values (6,'Finance',null,null,'SEOUL');
Insert into UMS.DEPARTMENT (DEPT_ID,DEPT_NAME,PARENT_ID,MANAGED_ID,LOCATION) values (7,'Research',null,null,'SEOUL');
Insert into UMS.DEPARTMENT (DEPT_ID,DEPT_NAME,PARENT_ID,MANAGED_ID,LOCATION) values (8,'Accounting',null,null,'BUSAN');
Insert into UMS.DEPARTMENT (DEPT_ID,DEPT_NAME,PARENT_ID,MANAGED_ID,LOCATION) values (9,'Marketing',null,null,'GWANGJOO');
Insert into UMS.DEPARTMENT (DEPT_ID,DEPT_NAME,PARENT_ID,MANAGED_ID,LOCATION) values (10,'Trade',null,null,'DAEJEON');
Insert into UMS.DEPARTMENT (DEPT_ID,DEPT_NAME,PARENT_ID,MANAGED_ID,LOCATION) values (11,'Administration',null,null,'SEOUL');
Insert into UMS.DEPARTMENT (DEPT_ID,DEPT_NAME,PARENT_ID,MANAGED_ID,LOCATION) values (12,'CM',null,null,'BUSAN');
Insert into UMS.DEPARTMENT (DEPT_ID,DEPT_NAME,PARENT_ID,MANAGED_ID,LOCATION) values (13,'Planning',null,null,'GWANGJOO');
Insert into UMS.DEPARTMENT (DEPT_ID,DEPT_NAME,PARENT_ID,MANAGED_ID,LOCATION) values (14,'Production',null,null,'DAEJEON');
Insert into UMS.DEPARTMENT (DEPT_ID,DEPT_NAME,PARENT_ID,MANAGED_ID,LOCATION) values (15,'Purchasing',null,null,'DAEGOO');
Insert into UMS.DEPARTMENT (DEPT_ID,DEPT_NAME,PARENT_ID,MANAGED_ID,LOCATION) values (16,'Finance',null,null,'SEOUL');
Insert into UMS.DEPARTMENT (DEPT_ID,DEPT_NAME,PARENT_ID,MANAGED_ID,LOCATION) values (17,'Research',null,null,'SEOUL');
Insert into UMS.DEPARTMENT (DEPT_ID,DEPT_NAME,PARENT_ID,MANAGED_ID,LOCATION) values (18,'Accounting',null,null,'BUSAN');
Insert into UMS.DEPARTMENT (DEPT_ID,DEPT_NAME,PARENT_ID,MANAGED_ID,LOCATION) values (19,'Marketing',null,null,'GWANGJOO');
Insert into UMS.DEPARTMENT (DEPT_ID,DEPT_NAME,PARENT_ID,MANAGED_ID,LOCATION) values (20,'Trade',null,null,'DAEJEON');
REM INSERTING into UMS.EMPLOYEES
SET DEFINE OFF;
Insert into UMS.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPT_ID) values (100,'��Ƽ��','ŷ','sking12','515.123.4567',to_date('87/01/09','RR/MM/DD'),'ad_pres',24000,null,null,90);
Insert into UMS.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPT_ID) values (101,'�ϳ�','��Ŀ','nkochhar','515.123.4568',to_date('90/02/08','RR/MM/DD'),'ad_vp',17000,null,100,90);
Insert into UMS.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPT_ID) values (102,'����','���̾�','ldehaannn','515.123.4569',to_date('92/03/08','RR/MM/DD'),'ad_vp',17000,null,100,90);
Insert into UMS.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPT_ID) values (103,'�˷����','�޳��','ahunold123','590.423.4567',to_date('93/04/08','RR/MM/DD'),'it_prog',9000,null,102,60);
Insert into UMS.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPT_ID) values (104,'�θ���','��Ͻ�Ʈ','bernst','590.423.4568',to_date('95/05/10','RR/MM/DD'),'it_prog',6000,null,103,60);
Insert into UMS.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPT_ID) values (107,'���̿���','�η���','dlorentz','590.423.5567',to_date('85/06/08','RR/MM/DD'),'it_prog',4200,null,103,60);
Insert into UMS.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPT_ID) values (124,'�ɺ�','����','kmourgos','650.123.5234',to_date('86/07/08','RR/MM/DD'),'st_man',5800,null,100,50);
Insert into UMS.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPT_ID) values (141,'Ʈ����','���ڽ�','trajs','650.121.8009',to_date('80/08/08','RR/MM/DD'),'st_clerk',3500,null,124,50);
Insert into UMS.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPT_ID) values (142,'����','���̺�','cdavies','650.121.2994',to_date('95/09/08','RR/MM/DD'),'st_clerk',3100,null,124,50);
Insert into UMS.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPT_ID) values (143,'����','���佺','rmatos','650.121.2874',to_date('96/10/08','RR/MM/DD'),'st_clerk',2600,null,124,50);
Insert into UMS.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPT_ID) values (144,'����','�ٰ���','pvargas','650.121.2004',to_date('20/11/08','RR/MM/DD'),'st_clerk',2500,null,124,50);
Insert into UMS.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPT_ID) values (149,'������','���Ű','ezlotkey','011.44.1344.429018',to_date('97/04/08','RR/MM/DD'),'sa_man',10500,0.2,100,80);
Insert into UMS.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPT_ID) values (174,'����','�ƺ�','eabel','011.44.1644.429267',to_date('21/05/08','RR/MM/DD'),'sa_rep',11000,0.3,149,80);
Insert into UMS.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPT_ID) values (176,'������','���Ϸ�','jtaylor','011.44.1644.429265',to_date('01/07/08','RR/MM/DD'),'sa_rep',8600,0.2,149,80);
Insert into UMS.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPT_ID) values (178,'Ŵ����','�׷�Ʈ','kgrant','011.44.1644.429263',to_date('97/03/08','RR/MM/DD'),'sa_rep',7000,0.15,149,null);
Insert into UMS.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPT_ID) values (200,'������','�Ҹ�','jwhalen','515.123.4444',to_date('98/08/08','RR/MM/DD'),'ad_asst',4400,null,101,10);
Insert into UMS.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPT_ID) values (201,'����Ŭ','�츣������','mhartste','515.123.5555',to_date('99/12/08','RR/MM/DD'),'mk_man',13000,null,100,20);
Insert into UMS.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPT_ID) values (202,'��','����','pfay','603.123.6666',to_date('88/11/08','RR/MM/DD'),'mk_rep',6000,null,201,20);
Insert into UMS.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPT_ID) values (205,'����','���佺','shiggins','515.123.8080',to_date('91/05/08','RR/MM/DD'),'ac_mgr',12000,null,101,110);
Insert into UMS.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,PHONE_NUMBER,HIRE_DATE,JOB_ID,SALARY,COMMISSION_PCT,MANAGER_ID,DEPT_ID) values (206,'������','������','wgietz','515.123.8181',to_date('02/06/08','RR/MM/DD'),'ac_account',8300,null,205,110);
REM INSERTING into UMS.INVOICEDETAIL
SET DEFINE OFF;
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (49,10,20,2000,1,2000,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (50,10,17,25000,2,50000,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (51,10,15,25000,3,75000,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (54,12,16,20000,12,240000,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (55,13,19,1000,2,2000,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (21,6,6,3000,1,3000,to_date('22/11/11','RR/MM/DD'),to_date('22/11/11','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (22,6,5,1000,2,2000,to_date('22/11/11','RR/MM/DD'),to_date('22/11/11','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (23,6,4,2000,3,6000,to_date('22/11/11','RR/MM/DD'),to_date('22/11/11','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (24,6,3,5000,4,20000,to_date('22/11/11','RR/MM/DD'),to_date('22/11/11','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (25,6,2,4000,5,20000,to_date('22/11/11','RR/MM/DD'),to_date('22/11/11','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (1,1,1,1000,3,3000,to_date('20/04/18','RR/MM/DD'),to_date('20/04/18','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (2,1,3,500,5,25000,to_date('20/04/18','RR/MM/DD'),to_date('20/04/18','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (3,2,1,100,30,300000,to_date('20/04/18','RR/MM/DD'),to_date('20/04/18','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (4,2,2,400,55,2200000,to_date('20/10/01','RR/MM/DD'),to_date('20/10/01','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (5,2,3,500,700,350000,to_date('20/10/01','RR/MM/DD'),to_date('20/10/01','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (6,2,4,1000,7580,75800,to_date('20/10/01','RR/MM/DD'),to_date('20/10/01','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (7,3,1,10000,1,10000,to_date('20/10/02','RR/MM/DD'),to_date('20/10/02','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (8,3,2,10000,34,340000,to_date('20/10/02','RR/MM/DD'),to_date('20/10/02','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (9,3,3,2000,5755,1151000,to_date('20/10/02','RR/MM/DD'),to_date('20/10/02','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (10,4,1,40000,200,80000,to_date('20/10/03','RR/MM/DD'),to_date('20/10/03','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (11,4,2,500,90,45000,to_date('20/10/03','RR/MM/DD'),to_date('20/10/03','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (12,4,3,2000,60,12000,to_date('20/10/03','RR/MM/DD'),to_date('20/10/03','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (13,4,4,300000,68,2040000,to_date('20/10/03','RR/MM/DD'),to_date('20/10/03','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (14,5,1,10000,33,33000,to_date('20/10/04','RR/MM/DD'),to_date('20/10/04','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (15,5,2,4000,44,176000,to_date('20/10/04','RR/MM/DD'),to_date('20/10/04','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (16,5,3,500,56,28000,to_date('20/10/04','RR/MM/DD'),to_date('20/10/04','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (26,7,6,3000,11,33000,to_date('22/11/11','RR/MM/DD'),to_date('22/11/11','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (27,7,5,1000,22,22000,to_date('22/11/11','RR/MM/DD'),to_date('22/11/11','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (28,7,2,4000,33,132000,to_date('22/11/11','RR/MM/DD'),to_date('22/11/11','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (29,7,3,5000,44,220000,to_date('22/11/11','RR/MM/DD'),to_date('22/11/11','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (41,8,20,2000,10,20000,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (42,8,19,1000,2,2000,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (43,8,17,25000,4,100000,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (44,9,20,2000,10,20000,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (45,9,19,1000,2,2000,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (46,9,17,25000,3,75000,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (47,9,15,25000,4,100000,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (48,9,12,50000,5,250000,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (52,11,20,2000,122,244000,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (53,11,17,25000,16,400000,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (56,14,14,2000,23,46000,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (57,14,11,30000,3,90000,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (58,15,15,25000,12,300000,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (59,16,17,25000,1,25000,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (60,16,10,1000,123,123000,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (61,17,5,1000,2,2000,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (62,17,1,37000,5,185000,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (63,17,10,1000,45,45000,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (64,18,20,2000,1,2000,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (65,18,11,30000,2,60000,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (66,19,20,2000,22,44000,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (67,20,20,2000,12,24000,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (68,21,20,2000,23,46000,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEDETAIL (INVOICE_DETAIL_ID,INVOICE_ID,PRODUCT_ID,UNIT_PRICE,QUANTITY,TOTAL_AMT,CREATED_DATE,MODIFIED_DATE) values (69,21,16,20000,34,680000,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
REM INSERTING into UMS.INVOICEHEADER
SET DEFINE OFF;
Insert into UMS.INVOICEHEADER (INVOICE_ID,CLIENT_ID,SHIPPING_ADDRESS,TOTAL_AMT,DESCRIPTION,CREATED_DATE,MODIFIED_DATE,INVOICE_DATE) values (10,4,null,127000,null,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEHEADER (INVOICE_ID,CLIENT_ID,SHIPPING_ADDRESS,TOTAL_AMT,DESCRIPTION,CREATED_DATE,MODIFIED_DATE,INVOICE_DATE) values (12,1,null,240000,null,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEHEADER (INVOICE_ID,CLIENT_ID,SHIPPING_ADDRESS,TOTAL_AMT,DESCRIPTION,CREATED_DATE,MODIFIED_DATE,INVOICE_DATE) values (13,1,null,2000,null,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEHEADER (INVOICE_ID,CLIENT_ID,SHIPPING_ADDRESS,TOTAL_AMT,DESCRIPTION,CREATED_DATE,MODIFIED_DATE,INVOICE_DATE) values (6,2,null,51000,null,to_date('22/11/11','RR/MM/DD'),to_date('22/11/11','RR/MM/DD'),to_date('22/11/11','RR/MM/DD'));
Insert into UMS.INVOICEHEADER (INVOICE_ID,CLIENT_ID,SHIPPING_ADDRESS,TOTAL_AMT,DESCRIPTION,CREATED_DATE,MODIFIED_DATE,INVOICE_DATE) values (1,1,'SEOUL 238-3',192500,null,to_date('20/04/18','RR/MM/DD'),to_date('20/04/18','RR/MM/DD'),to_date('22/11/09','RR/MM/DD'));
Insert into UMS.INVOICEHEADER (INVOICE_ID,CLIENT_ID,SHIPPING_ADDRESS,TOTAL_AMT,DESCRIPTION,CREATED_DATE,MODIFIED_DATE,INVOICE_DATE) values (2,2,'NEW YORK 238-3',7865000,null,to_date('20/10/01','RR/MM/DD'),to_date('20/10/01','RR/MM/DD'),to_date('22/11/09','RR/MM/DD'));
Insert into UMS.INVOICEHEADER (INVOICE_ID,CLIENT_ID,SHIPPING_ADDRESS,TOTAL_AMT,DESCRIPTION,CREATED_DATE,MODIFIED_DATE,INVOICE_DATE) values (3,2,'PARIS 3837-3',1186000,null,to_date('20/10/02','RR/MM/DD'),to_date('20/10/02','RR/MM/DD'),to_date('22/11/09','RR/MM/DD'));
Insert into UMS.INVOICEHEADER (INVOICE_ID,CLIENT_ID,SHIPPING_ADDRESS,TOTAL_AMT,DESCRIPTION,CREATED_DATE,MODIFIED_DATE,INVOICE_DATE) values (4,3,'TOKOY 100-2',285650,null,to_date('20/10/03','RR/MM/DD'),to_date('20/10/03','RR/MM/DD'),to_date('22/11/09','RR/MM/DD'));
Insert into UMS.INVOICEHEADER (INVOICE_ID,CLIENT_ID,SHIPPING_ADDRESS,TOTAL_AMT,DESCRIPTION,CREATED_DATE,MODIFIED_DATE,INVOICE_DATE) values (5,5,'ITALY 93-1',778500,null,to_date('20/10/04','RR/MM/DD'),to_date('20/10/04','RR/MM/DD'),to_date('22/11/09','RR/MM/DD'));
Insert into UMS.INVOICEHEADER (INVOICE_ID,CLIENT_ID,SHIPPING_ADDRESS,TOTAL_AMT,DESCRIPTION,CREATED_DATE,MODIFIED_DATE,INVOICE_DATE) values (7,3,null,407000,null,to_date('22/11/11','RR/MM/DD'),to_date('22/11/11','RR/MM/DD'),to_date('22/11/11','RR/MM/DD'));
Insert into UMS.INVOICEHEADER (INVOICE_ID,CLIENT_ID,SHIPPING_ADDRESS,TOTAL_AMT,DESCRIPTION,CREATED_DATE,MODIFIED_DATE,INVOICE_DATE) values (8,2,null,122000,'���� �κ��̽� ',to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEHEADER (INVOICE_ID,CLIENT_ID,SHIPPING_ADDRESS,TOTAL_AMT,DESCRIPTION,CREATED_DATE,MODIFIED_DATE,INVOICE_DATE) values (9,1,null,447000,null,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'),to_date('22/11/13','RR/MM/DD'));
Insert into UMS.INVOICEHEADER (INVOICE_ID,CLIENT_ID,SHIPPING_ADDRESS,TOTAL_AMT,DESCRIPTION,CREATED_DATE,MODIFIED_DATE,INVOICE_DATE) values (11,4,null,644000,null,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEHEADER (INVOICE_ID,CLIENT_ID,SHIPPING_ADDRESS,TOTAL_AMT,DESCRIPTION,CREATED_DATE,MODIFIED_DATE,INVOICE_DATE) values (14,2,null,136000,null,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEHEADER (INVOICE_ID,CLIENT_ID,SHIPPING_ADDRESS,TOTAL_AMT,DESCRIPTION,CREATED_DATE,MODIFIED_DATE,INVOICE_DATE) values (15,1,null,300000,null,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEHEADER (INVOICE_ID,CLIENT_ID,SHIPPING_ADDRESS,TOTAL_AMT,DESCRIPTION,CREATED_DATE,MODIFIED_DATE,INVOICE_DATE) values (16,5,null,148000,null,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEHEADER (INVOICE_ID,CLIENT_ID,SHIPPING_ADDRESS,TOTAL_AMT,DESCRIPTION,CREATED_DATE,MODIFIED_DATE,INVOICE_DATE) values (17,3,null,232000,null,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEHEADER (INVOICE_ID,CLIENT_ID,SHIPPING_ADDRESS,TOTAL_AMT,DESCRIPTION,CREATED_DATE,MODIFIED_DATE,INVOICE_DATE) values (18,1,null,62000,null,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEHEADER (INVOICE_ID,CLIENT_ID,SHIPPING_ADDRESS,TOTAL_AMT,DESCRIPTION,CREATED_DATE,MODIFIED_DATE,INVOICE_DATE) values (19,1,null,44000,null,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEHEADER (INVOICE_ID,CLIENT_ID,SHIPPING_ADDRESS,TOTAL_AMT,DESCRIPTION,CREATED_DATE,MODIFIED_DATE,INVOICE_DATE) values (20,1,null,24000,null,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
Insert into UMS.INVOICEHEADER (INVOICE_ID,CLIENT_ID,SHIPPING_ADDRESS,TOTAL_AMT,DESCRIPTION,CREATED_DATE,MODIFIED_DATE,INVOICE_DATE) values (21,3,null,726000,null,to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'));
REM INSERTING into UMS.JOBS
SET DEFINE OFF;
Insert into UMS.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY) values ('AD_PRES','President',20000,40000);
Insert into UMS.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY) values ('AD_VP','Administration Vice President',15000,30000);
Insert into UMS.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY) values ('AD_ASST','Administration Assistant',3000,6000);
Insert into UMS.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY) values ('AC_MGR','Accounting Manager',8200,16000);
Insert into UMS.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY) values ('AC_ACCOUNT','Public Accountant',4200,9000);
Insert into UMS.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY) values ('SA_MAN','Sales Manager',10000,20000);
Insert into UMS.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY) values ('SA_REP','Sales Representative',6000,12000);
Insert into UMS.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY) values ('ST_MAN','Stock Manager',5500,8500);
Insert into UMS.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY) values ('ST_CLERK','Stock Clerk',2000,5000);
Insert into UMS.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY) values ('IT_PROG','Programmer',4000,10000);
Insert into UMS.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY) values ('MK_MAN','Marketing Manager',9000,15000);
Insert into UMS.JOBS (JOB_ID,JOB_TITLE,MIN_SALARY,MAX_SALARY) values ('MK_REP','Marketing Representative',4000,9000);
REM INSERTING into UMS.PERSISTENT_LOGINS
SET DEFINE OFF;
REM INSERTING into UMS.PRODUCT
SET DEFINE OFF;
Insert into UMS.PRODUCT (PRODUCT_ID,PRODUCT_NAME,BRAND,DESCRIPTION,UNIT_PRICE,CATEGORY_ID,IS_ACTIVE,RECEIPT_DATE) values (1,'Refrigerator',null,null,37000,1,'1  ',to_date('22/11/09','RR/MM/DD'));
Insert into UMS.PRODUCT (PRODUCT_ID,PRODUCT_NAME,BRAND,DESCRIPTION,UNIT_PRICE,CATEGORY_ID,IS_ACTIVE,RECEIPT_DATE) values (2,'Air Conditioner',null,null,4000,1,'1  ',to_date('22/11/09','RR/MM/DD'));
Insert into UMS.PRODUCT (PRODUCT_ID,PRODUCT_NAME,BRAND,DESCRIPTION,UNIT_PRICE,CATEGORY_ID,IS_ACTIVE,RECEIPT_DATE) values (3,'Fan',null,null,5000,1,'1  ',to_date('22/11/09','RR/MM/DD'));
Insert into UMS.PRODUCT (PRODUCT_ID,PRODUCT_NAME,BRAND,DESCRIPTION,UNIT_PRICE,CATEGORY_ID,IS_ACTIVE,RECEIPT_DATE) values (4,'LED TV',null,null,2000,1,'1  ',to_date('22/11/09','RR/MM/DD'));
Insert into UMS.PRODUCT (PRODUCT_ID,PRODUCT_NAME,BRAND,DESCRIPTION,UNIT_PRICE,CATEGORY_ID,IS_ACTIVE,RECEIPT_DATE) values (5,'LCD TV',null,null,1000,1,'1  ',to_date('22/11/09','RR/MM/DD'));
Insert into UMS.PRODUCT (PRODUCT_ID,PRODUCT_NAME,BRAND,DESCRIPTION,UNIT_PRICE,CATEGORY_ID,IS_ACTIVE,RECEIPT_DATE) values (6,'OLED TV',null,null,3000,1,'1  ',to_date('22/11/09','RR/MM/DD'));
Insert into UMS.PRODUCT (PRODUCT_ID,PRODUCT_NAME,BRAND,DESCRIPTION,UNIT_PRICE,CATEGORY_ID,IS_ACTIVE,RECEIPT_DATE) values (7,'Bicycle',null,null,1000,1,'1  ',to_date('22/11/09','RR/MM/DD'));
Insert into UMS.PRODUCT (PRODUCT_ID,PRODUCT_NAME,BRAND,DESCRIPTION,UNIT_PRICE,CATEGORY_ID,IS_ACTIVE,RECEIPT_DATE) values (8,'Desk',null,null,3000,1,'1  ',to_date('22/11/09','RR/MM/DD'));
Insert into UMS.PRODUCT (PRODUCT_ID,PRODUCT_NAME,BRAND,DESCRIPTION,UNIT_PRICE,CATEGORY_ID,IS_ACTIVE,RECEIPT_DATE) values (9,'Chair',null,null,2000,1,'1  ',to_date('22/11/09','RR/MM/DD'));
Insert into UMS.PRODUCT (PRODUCT_ID,PRODUCT_NAME,BRAND,DESCRIPTION,UNIT_PRICE,CATEGORY_ID,IS_ACTIVE,RECEIPT_DATE) values (10,'Shoes',null,null,1000,1,'1  ',to_date('22/11/09','RR/MM/DD'));
Insert into UMS.PRODUCT (PRODUCT_ID,PRODUCT_NAME,BRAND,DESCRIPTION,UNIT_PRICE,CATEGORY_ID,IS_ACTIVE,RECEIPT_DATE) values (11,'Car',null,null,30000,1,'1  ',to_date('22/11/09','RR/MM/DD'));
Insert into UMS.PRODUCT (PRODUCT_ID,PRODUCT_NAME,BRAND,DESCRIPTION,UNIT_PRICE,CATEGORY_ID,IS_ACTIVE,RECEIPT_DATE) values (12,'Lorry',null,null,50000,1,'1  ',to_date('22/11/09','RR/MM/DD'));
Insert into UMS.PRODUCT (PRODUCT_ID,PRODUCT_NAME,BRAND,DESCRIPTION,UNIT_PRICE,CATEGORY_ID,IS_ACTIVE,RECEIPT_DATE) values (13,'Motorcycle',null,null,5000,1,'1  ',to_date('22/11/09','RR/MM/DD'));
Insert into UMS.PRODUCT (PRODUCT_ID,PRODUCT_NAME,BRAND,DESCRIPTION,UNIT_PRICE,CATEGORY_ID,IS_ACTIVE,RECEIPT_DATE) values (14,'DeskTop',null,null,2000,1,'1  ',to_date('22/11/09','RR/MM/DD'));
Insert into UMS.PRODUCT (PRODUCT_ID,PRODUCT_NAME,BRAND,DESCRIPTION,UNIT_PRICE,CATEGORY_ID,IS_ACTIVE,RECEIPT_DATE) values (15,'NoteBook',null,null,25000,1,'1  ',to_date('22/11/09','RR/MM/DD'));
Insert into UMS.PRODUCT (PRODUCT_ID,PRODUCT_NAME,BRAND,DESCRIPTION,UNIT_PRICE,CATEGORY_ID,IS_ACTIVE,RECEIPT_DATE) values (16,'DeskTop',null,null,20000,1,'1  ',to_date('22/11/09','RR/MM/DD'));
Insert into UMS.PRODUCT (PRODUCT_ID,PRODUCT_NAME,BRAND,DESCRIPTION,UNIT_PRICE,CATEGORY_ID,IS_ACTIVE,RECEIPT_DATE) values (17,'NoteBook',null,null,25000,1,'1  ',to_date('22/11/09','RR/MM/DD'));
Insert into UMS.PRODUCT (PRODUCT_ID,PRODUCT_NAME,BRAND,DESCRIPTION,UNIT_PRICE,CATEGORY_ID,IS_ACTIVE,RECEIPT_DATE) values (18,'Rice',null,null,3000,1,'1  ',to_date('22/11/09','RR/MM/DD'));
Insert into UMS.PRODUCT (PRODUCT_ID,PRODUCT_NAME,BRAND,DESCRIPTION,UNIT_PRICE,CATEGORY_ID,IS_ACTIVE,RECEIPT_DATE) values (19,'Vegetable',null,null,1000,1,'1  ',to_date('22/11/09','RR/MM/DD'));
Insert into UMS.PRODUCT (PRODUCT_ID,PRODUCT_NAME,BRAND,DESCRIPTION,UNIT_PRICE,CATEGORY_ID,IS_ACTIVE,RECEIPT_DATE) values (20,'Flower',null,null,2000,1,'1  ',to_date('22/11/09','RR/MM/DD'));
Insert into UMS.PRODUCT (PRODUCT_ID,PRODUCT_NAME,BRAND,DESCRIPTION,UNIT_PRICE,CATEGORY_ID,IS_ACTIVE,RECEIPT_DATE) values (21,'���ο� ��ǰ02','SAMSUNG','����2',2000000,1,'1  ',to_date('22/11/15','RR/MM/DD'));
Insert into UMS.PRODUCT (PRODUCT_ID,PRODUCT_NAME,BRAND,DESCRIPTION,UNIT_PRICE,CATEGORY_ID,IS_ACTIVE,RECEIPT_DATE) values (22,'���ο� ��ǰ02','SAMSUNG','����2',2000000,1,'1  ',to_date('22/11/15','RR/MM/DD'));
Insert into UMS.PRODUCT (PRODUCT_ID,PRODUCT_NAME,BRAND,DESCRIPTION,UNIT_PRICE,CATEGORY_ID,IS_ACTIVE,RECEIPT_DATE) values (23,'���ο� ��ǰ02','SAMSUNG','����2',2000000,1,'1  ',to_date('22/11/15','RR/MM/DD'));
Insert into UMS.PRODUCT (PRODUCT_ID,PRODUCT_NAME,BRAND,DESCRIPTION,UNIT_PRICE,CATEGORY_ID,IS_ACTIVE,RECEIPT_DATE) values (24,'���ο� ��ǰ02','SAMSUNG','����2',2000000,1,'1  ',to_date('22/11/15','RR/MM/DD'));
REM INSERTING into UMS.ROLE
SET DEFINE OFF;
Insert into UMS.ROLE (ROLE_ID,ROLE_NAME) values ('1','ROLE_ADMIN');
Insert into UMS.ROLE (ROLE_ID,ROLE_NAME) values ('2','ROLE_USER');
Insert into UMS.ROLE (ROLE_ID,ROLE_NAME) values ('3','USER');
REM INSERTING into UMS.USERS
SET DEFINE OFF;
Insert into UMS.USERS (USER_NO,USER_ID,USER_PWD,USER_NAME,EMAIL,PHONE,FAX,ZIP_NUM,ADDRESS1,ADDRESS2,DEPT_ID,ROLE_ID,IMAGE_PATH,USEYN,REGDATE,MODDATE,ENAVLED) values (8,'java10','$2a$10$lO4UdSncTsjzXKpBhiQ6j.fOJnoLNDOUxFXB0VI8R2LEo.2f66ura','ȫ���',null,null,null,null,null,null,1,'1',null,'1  ',to_date('22/11/15','RR/MM/DD'),to_date('22/11/15','RR/MM/DD'),1);
Insert into UMS.USERS (USER_NO,USER_ID,USER_PWD,USER_NAME,EMAIL,PHONE,FAX,ZIP_NUM,ADDRESS1,ADDRESS2,DEPT_ID,ROLE_ID,IMAGE_PATH,USEYN,REGDATE,MODDATE,ENAVLED) values (1,'java','$2a$10$rADXSVmovoCSm3.IYqbwyev5P1yRJCbeyAWQRQKVx9mdl2BdQ9FHe','magicoh','a@a.com','010','02',null,null,null,1,'ROLE_ADMIN',null,'1  ',to_date('22/11/09','RR/MM/DD'),to_date('22/11/09','RR/MM/DD'),1);
Insert into UMS.USERS (USER_NO,USER_ID,USER_PWD,USER_NAME,EMAIL,PHONE,FAX,ZIP_NUM,ADDRESS1,ADDRESS2,DEPT_ID,ROLE_ID,IMAGE_PATH,USEYN,REGDATE,MODDATE,ENAVLED) values (3,'java7','$2a$10$vOTZBn/EPSs5EFRffIuZYuPOPBkoCbcTnyCmVnWUW2FsmZpmSN4t.','�ڹ�7','a@a.com','010-2222-3334',null,'134-765','���� ������ ��2�� ������ũ����Ʈ','��2�� ������ũ����Ʈ 302',1,'ROLE_USER',null,'1  ',to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'),1);
Insert into UMS.USERS (USER_NO,USER_ID,USER_PWD,USER_NAME,EMAIL,PHONE,FAX,ZIP_NUM,ADDRESS1,ADDRESS2,DEPT_ID,ROLE_ID,IMAGE_PATH,USEYN,REGDATE,MODDATE,ENAVLED) values (4,'java8','$2a$10$.t3UhshgIa9InewypEPDwuv8hg/hHxa0TZkNPS49WoxTEvkc6v2Aa','ȫ�湮','abc@a.com','010-2222-3333',null,'134-766','���� ������ ��2�� �ŵ��ƾ���Ʈ','��2�� �ŵ��ƾ���Ʈ 302',1,'ROLE_USER',null,'1  ',to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'),1);
Insert into UMS.USERS (USER_NO,USER_ID,USER_PWD,USER_NAME,EMAIL,PHONE,FAX,ZIP_NUM,ADDRESS1,ADDRESS2,DEPT_ID,ROLE_ID,IMAGE_PATH,USEYN,REGDATE,MODDATE,ENAVLED) values (5,'java9','$2a$10$RT3P8Xs.5FVKcmtJfRAq7.yfuPbZnKAHEyxBlGjWFfpJzUhmc.TNe','�ڹ�9','abcd@a.com','010-2222-3333',null,'134-770','���� ������ ��2�� �����������̾���Ʈ','��2�� �����������̾���Ʈ 307��',1,'ROLE_USER',null,'1  ',to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'),1);
Insert into UMS.USERS (USER_NO,USER_ID,USER_PWD,USER_NAME,EMAIL,PHONE,FAX,ZIP_NUM,ADDRESS1,ADDRESS2,DEPT_ID,ROLE_ID,IMAGE_PATH,USEYN,REGDATE,MODDATE,ENAVLED) values (6,'java10','$2a$10$1wFYxaA5XGpGgMorCswJ4..1RhjvltSMn0Z6TMkTN5AAwx9fmWGH.','�ڹ�10','abcd@a.com','010-2222-3333',null,'134-770','���� ������ ��2�� �����������̾���Ʈ','��2�� �����������̾���Ʈ 307��',1,'ROLE_USER',null,'1  ',to_date('22/11/14','RR/MM/DD'),to_date('22/11/14','RR/MM/DD'),1);
REM INSERTING into UMS.USER_ROLE
SET DEFINE OFF;
Insert into UMS.USER_ROLE (USER_ROLE_ID,USER_ID,ROLE_ID) values (1,'java','ROLE_USER');
Insert into UMS.USER_ROLE (USER_ROLE_ID,USER_ID,ROLE_ID) values (2,'admin','ROLE_ADMIN');
Insert into UMS.USER_ROLE (USER_ROLE_ID,USER_ID,ROLE_ID) values (4,'java7','ROLE_USER');
Insert into UMS.USER_ROLE (USER_ROLE_ID,USER_ID,ROLE_ID) values (8,'java9','ROLE_USER');
Insert into UMS.USER_ROLE (USER_ROLE_ID,USER_ID,ROLE_ID) values (6,'java8','ROLE_USER');
Insert into UMS.USER_ROLE (USER_ROLE_ID,USER_ID,ROLE_ID) values (7,'java9','ROLE_USER');
--------------------------------------------------------
--  DDL for Index SYS_C0010360
--------------------------------------------------------

  CREATE UNIQUE INDEX "UMS"."SYS_C0010360" ON "UMS"."BBS" ("NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CATEGORY
--------------------------------------------------------

  CREATE UNIQUE INDEX "UMS"."PK_CATEGORY" ON "UMS"."CATEGORY" ("CATEGORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_CLIENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "UMS"."PK_CLIENT" ON "UMS"."CLIENT" ("CLIENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_DEPARTMENT
--------------------------------------------------------

  CREATE UNIQUE INDEX "UMS"."PK_DEPARTMENT" ON "UMS"."DEPARTMENT" ("DEPT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_INVOICE_DETAIL_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "UMS"."PK_INVOICE_DETAIL_ID" ON "UMS"."INVOICEDETAIL" ("INVOICE_DETAIL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_INVOICEHEADER
--------------------------------------------------------

  CREATE UNIQUE INDEX "UMS"."PK_INVOICEHEADER" ON "UMS"."INVOICEHEADER" ("INVOICE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index JOB_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UMS"."JOB_ID_PK" ON "UMS"."JOBS" ("JOB_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0010364
--------------------------------------------------------

  CREATE UNIQUE INDEX "UMS"."SYS_C0010364" ON "UMS"."PERSISTENT_LOGINS" ("SERIES") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_PRODUCT_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "UMS"."PK_PRODUCT_ID" ON "UMS"."PRODUCT" ("PRODUCT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_ROLE_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "UMS"."PK_ROLE_ID" ON "UMS"."ROLE" ("ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_USER_NO
--------------------------------------------------------

  CREATE UNIQUE INDEX "UMS"."PK_USER_NO" ON "UMS"."USERS" ("USER_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_USER_ROLE_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "UMS"."PK_USER_ROLE_ID" ON "UMS"."USER_ROLE" ("USER_ROLE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BBS
--------------------------------------------------------

  ALTER TABLE "UMS"."BBS" ADD PRIMARY KEY ("NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "UMS"."BBS" MODIFY ("TITLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CATEGORY
--------------------------------------------------------

  ALTER TABLE "UMS"."CATEGORY" ADD CONSTRAINT "PK_CATEGORY" PRIMARY KEY ("CATEGORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "UMS"."CATEGORY" MODIFY ("CATEGORY_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "UMS"."CLIENT" ADD CONSTRAINT "PK_CLIENT" PRIMARY KEY ("CLIENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "UMS"."CLIENT" MODIFY ("CLIENT_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DEPARTMENT
--------------------------------------------------------

  ALTER TABLE "UMS"."DEPARTMENT" ADD CONSTRAINT "PK_DEPARTMENT" PRIMARY KEY ("DEPT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "UMS"."DEPARTMENT" MODIFY ("DEPT_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INVOICEDETAIL
--------------------------------------------------------

  ALTER TABLE "UMS"."INVOICEDETAIL" ADD CONSTRAINT "PK_INVOICE_DETAIL_ID" PRIMARY KEY ("INVOICE_DETAIL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "UMS"."INVOICEDETAIL" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table INVOICEHEADER
--------------------------------------------------------

  ALTER TABLE "UMS"."INVOICEHEADER" ADD CONSTRAINT "PK_INVOICEHEADER" PRIMARY KEY ("INVOICE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "UMS"."INVOICEHEADER" MODIFY ("TOTAL_AMT" NOT NULL ENABLE);
  ALTER TABLE "UMS"."INVOICEHEADER" MODIFY ("CLIENT_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table JOBS
--------------------------------------------------------

  ALTER TABLE "UMS"."JOBS" ADD CONSTRAINT "JOB_ID_PK" PRIMARY KEY ("JOB_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "UMS"."JOBS" MODIFY ("JOB_TITLE" CONSTRAINT "JOB_TITLE_NN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSISTENT_LOGINS
--------------------------------------------------------

  ALTER TABLE "UMS"."PERSISTENT_LOGINS" ADD PRIMARY KEY ("SERIES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "UMS"."PERSISTENT_LOGINS" MODIFY ("LAST_USED" NOT NULL ENABLE);
  ALTER TABLE "UMS"."PERSISTENT_LOGINS" MODIFY ("TOKEN" NOT NULL ENABLE);
  ALTER TABLE "UMS"."PERSISTENT_LOGINS" MODIFY ("USER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "UMS"."PRODUCT" ADD CONSTRAINT "PK_PRODUCT_ID" PRIMARY KEY ("PRODUCT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "UMS"."PRODUCT" MODIFY ("PRODUCT_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ROLE
--------------------------------------------------------

  ALTER TABLE "UMS"."ROLE" ADD CONSTRAINT "PK_ROLE_ID" PRIMARY KEY ("ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "UMS"."ROLE" MODIFY ("ROLE_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "UMS"."USERS" ADD CONSTRAINT "PK_USER_NO" PRIMARY KEY ("USER_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "UMS"."USERS" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "UMS"."USERS" MODIFY ("USER_PWD" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table USER_ROLE
--------------------------------------------------------

  ALTER TABLE "UMS"."USER_ROLE" ADD CONSTRAINT "PK_USER_ROLE_ID" PRIMARY KEY ("USER_ROLE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INVOICEDETAIL
--------------------------------------------------------

  ALTER TABLE "UMS"."INVOICEDETAIL" ADD CONSTRAINT "FK_INVOICE_ID" FOREIGN KEY ("INVOICE_ID")
	  REFERENCES "UMS"."INVOICEHEADER" ("INVOICE_ID") ENABLE;
  ALTER TABLE "UMS"."INVOICEDETAIL" ADD CONSTRAINT "FK_PRODUCT_ID" FOREIGN KEY ("PRODUCT_ID")
	  REFERENCES "UMS"."PRODUCT" ("PRODUCT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INVOICEHEADER
--------------------------------------------------------

  ALTER TABLE "UMS"."INVOICEHEADER" ADD CONSTRAINT "FK_CLIENT_ID" FOREIGN KEY ("CLIENT_ID")
	  REFERENCES "UMS"."CLIENT" ("CLIENT_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCT
--------------------------------------------------------

  ALTER TABLE "UMS"."PRODUCT" ADD CONSTRAINT "FK_CATEGORY_ID" FOREIGN KEY ("CATEGORY_ID")
	  REFERENCES "UMS"."CATEGORY" ("CATEGORY_ID") ENABLE;
